import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// primreact
import { PrimeReactProvider } from "primereact/api";
import "primereact/resources/themes/lara-light-blue/theme.css";
import 'primeicons/primeicons.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <PrimeReactProvider>
                <head>
                    <script
                        dangerouslySetInnerHTML={{
                            __html: `
                            const style = document.createElement('style')
                            style.innerHTML = '@layer tailwind-base, primereact, tailwind-utilities;'
                            style.setAttribute('type', 'text/css')
                            document.querySelector('head').prepend(style)
                            `,
                        }}
                    />
                </head>
                <body>
                    {children}
                </body>
            </PrimeReactProvider>
        </html>
    );
}
